import {
  StateGraph,
  StateSchema,
  type GraphNode,
  START,
  END,
} from "@langchain/langgraph";

import { z } from "zod";
import { HumanMessage, createAgent, providerStrategy } from "langchain";

import {
  geminiModel,
  mistralModel,
  cohereModel,
} from "./model.ai.js";

const state = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  const [mistralResponse, cohereResponse] = await Promise.all([
    mistralModel.invoke(state.problem),
    cohereModel.invoke(state.problem),
  ]);

  return {
    solution_1: String(mistralResponse.content),
    solution_2: String(cohereResponse.content),
  };
};

const judge = createAgent({
  model: geminiModel,
  responseFormat: providerStrategy(
    z.object({
      solution_1_score: z.number().min(0).max(10),
      solution_2_score: z.number().min(0).max(10),
      solution_1_reasoning: z.string(),
      solution_2_reasoning: z.string(),
    })
  ),
  systemPrompt: `
You are a judge tasked with evaluating two solutions generated by different AI models.

Provide:
- A score out of 10 for Solution 1.
- A score out of 10 for Solution 2.
- Reasoning for both scores.
`,
});

const judgeNode: GraphNode<typeof state> = async (state) => {
  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(`
Problem:
${state.problem}

Solution 1:
${state.solution_1}

Solution 2:
${state.solution_2}

Please evaluate both solutions and provide scores and reasoning.
      `),
    ],
  });

  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = judgeResponse.structuredResponse;

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
    },
  };
};

const graph = new StateGraph(state)
  .addNode("solutionNode", solutionNode)
  .addNode("judge_node", judgeNode)
  .addEdge(START, "solutionNode")
  .addEdge("solutionNode", "judge_node")
  .addEdge("judge_node", END)
  .compile();

export default async function runGraph(problem: string) {
  const result = await graph.invoke({
    problem,
  });

  return result;
}